#
import matplotlib.pyplot as plt
from pathlib import Path
from datetime import datetime
from pipeline_utils import YAMLDict, capture_args
from collections import defaultdict, OrderedDict
from pathlib import Path
from pipeline_utils import combine_tiffs
from tifffile import imread, imsave

import matplotlib.pyplot as plt
import seaborn as sns 

import cv2 as cv
import caiman as cm
import numpy as np
from scipy.ndimage import median_filter
from pipeline_utils import remove_neurons, draw_masks
import copy
import os
import yaml


def unwrap(obj):
    #if isinstance(obj, YAMLDictInner):
    #    return {k: unwrap(v) for k, v in obj.items()}
    if isinstance(obj, dict):
        return {k: unwrap(v) for k, v in obj.items()}
    elif isinstance(obj, Path):
        return str(obj)
    elif isinstance(obj, list):
        return [unwrap(o) for o in obj]
    else:
        return obj

def _get_provenance(output_dir):
    filepath = Path(output_dir) / 'provenance.yaml'
    if os.path.exists(filepath):
        with open(filepath, "r") as f:
            provenance = defaultdict(lambda : None, yaml.safe_load(f))
    else:
        provenance = defaultdict(lambda : None)

    return provenance    

def _save_provenance(provenance):
    filepath = Path(provenance['output_dir']) / 'provenance.yaml'
    with open(filepath, "w") as f:
        yaml.safe_dump(unwrap(provenance), f, default_flow_style=False)


def init(output_dir=None): 
    if output_dir is None:
        output_dir = "run-" + datetime.now().strftime('%m-%d-%H%M%S')
    
    output_dir = Path(output_dir)    
    output_dir.mkdir(exist_ok=True)

    provenance = _get_provenance(output_dir)
    if 'output_dir' not in provenance:
        provenance['output_dir'] = output_dir

    _save_provenance(provenance)
    return provenance



# 
def _load_data(filenames, ch_dict, z, multi_crop, multi_crop_start, **kwargs):
    data = {}
    for ch in ch_dict.values(): 
        data[ch] = {z : OrderedDict()} 
        for i, _ in enumerate(filenames):
            filename = filenames[i][z][ch]
            imgs = imread(filename).squeeze()
    
            if multi_crop:
                data[ch][i] = imgs[multi_crop_start[i]:, :, :]  
            else:
                data[ch][i] = imgs

    return data                

@capture_args
def load_data(provenance, multi_path, ch_dict, z, multi_crop=False, multi_crop_start=None, **kwargs): 
    if not provenance['load_data']:
        provenance['load_data'] = {}

    if 'filenames' in provenance['load_data']:
        filenames = provenance['load_data']['filenames']    
    else:
        multi_path = [Path(session) for session in multi_path]
        filenames = {}
        for i, session in enumerate(multi_path):
            filenames[i] = combine_tiffs(session, save_dir=Path(provenance['output_dir']))

    data = _load_data(filenames, ch_dict, z, multi_crop, multi_crop_start)

    provenance['load_data']['args'] = kwargs['__args_dict']
    provenance['load_data']['filenames'] = filenames 

    _save_provenance(provenance)
    return provenance, data      




#
def restore_affine_correction(provenance, z):
    affcorr_results_filenames = provenance['affine_motion_correction'][z]['filenames']
    affcorr_results = copy.deepcopy(affcorr_results_filenames)

    def replace_filenames_with_results(results):
        for k, v in results.items():
            if isinstance(v, dict):
                results[k] = replace_filenames_with_results(v)
            else:
                results[k] = imread(v).squeeze()

        return results        

    affcorr_results = replace_filenames_with_results(affcorr_results)  
    return affcorr_results 

def affine_motion_correction(provenance, z, data, **kwargs):
    """
    Iterates over the sessions that were defined in multi_path.
    For each session, a reference image is generated by averaging the middle 50% of frames.
    The reference image is appended to the beginning of the stack and the StackReg affine motion correction
    runs using this images as the reference.
    Then we apply the transform discovered with the motion correction channel to the mc channel and the functional channel
    Then we chop the first frame back off and we ought to have affine motion corrected tiffs for both channels for all sessions.
    """
    from pystackreg import StackReg

    if not provenance['affine_motion_correction']:
        provenance['affine_motion_correction'] = {}

    if z not in provenance['affine_motion_correction']:
        provenance['affine_motion_correction'][z] = {}

    if 'filenames' in provenance['affine_motion_correction'][z]:
        affcorr_results = restore_affine_correction(provenance, z)   
        return provenance, affcorr_results  
            
    out_mcch = {}
    out_fch = {}
    
    output_dir = Path(provenance['output_dir']) / z
    output_dir.mkdir(exist_ok=True)
    prov = provenance['load_data']['args']
    ch_dict = prov['ch_dict']
    multi_path = [Path(session) for session in prov['multi_path']]
    
    affcorr_results_filenames = {}
    affcorr_results = {}
    for ch in ch_dict.values():
        affcorr_results_filenames[ch] = OrderedDict()
        affcorr_results[ch] = OrderedDict()

    for i, p in enumerate(multi_path):
        refsize = np.ceil(np.size(data[ch_dict['mc_ch']][i],0)/2)

        # create 'ref' which is the mean of the middle 50% of images (approximately)
        ref = np.mean( data[ch_dict['mc_ch']][i][ int(np.ceil(refsize/2)):int(np.ceil(refsize/2)+refsize), :, : ], 0 )
        toreg_mc = data[ch_dict['mc_ch']][i]

        # have to put ref as first frame because sr will not accept a reference image I created
        firstframetrick_mc = np.vstack([ref[np.newaxis,...], toreg_mc]) 
        
        #Affine transformation
        sr = StackReg(StackReg.AFFINE)
        out_aff = sr.register_stack(firstframetrick_mc, reference='first')
        out_mcch[i] = sr.transform_stack(firstframetrick_mc)
        affcorr_results[ch_dict['mc_ch']][i] = out_mcch[i][1:,:,:]

        mc_fname = output_dir / f'{p.name}_{ch_dict["mc_ch"]}-affcorr_results.ome.tif'
        affcorr_results_filenames[ch_dict['mc_ch']][i] = mc_fname
        imsave(mc_fname, affcorr_results[ch_dict['mc_ch']][i])

        toreg_fc = data[ch_dict['func_ch']][i]
        firstframetrick_fc = np.vstack([ref[np.newaxis,...], toreg_fc])
        out_fch[i] = sr.transform_stack(firstframetrick_fc)
        affcorr_results[ch_dict['func_ch']][i] = out_fch[i][1:,:,:] 


        func_fname = output_dir / f'{p.name}_{ch_dict["func_ch"]}-affcorr_results.ome.tif'
        affcorr_results_filenames[ch_dict['func_ch']][i] = func_fname
        imsave(func_fname, affcorr_results[ch_dict['func_ch']][i])


    #provenance['affine_motion_correction']['args'] = kwargs['__args_dict']
    provenance['affine_motion_correction'][z]['filenames'] = affcorr_results_filenames  

    _save_provenance(provenance)
    return provenance, affcorr_results 



#
   

def _save_rigid_motion_correction_video(output_dir, func_ch, func_ch_file, z, path, anchor=(50,50), wd=0, 
                                        ht=0, t_stim_st=31, t_stim_end=211, ds_ratio=0.5, speed_up=20, frame_period=0.585):

    """
    "anchor":  # where to anchor the stim bar    
    "wd" : # width and height of the stim bar
    "ht": 
    "t_stim_st" : # time in seconds of the start of the stim
    "t_stim_end" :  # time in seconds of the end of the stim
    "ds_ratio":   # the fraction of frames to show in the video
    "speed_up":    # how much to speed up the video by
    "frame_period":  # time in seconds between frames, get this from the xml file
    """

    import imageio 

    fr = 1/frame_period
    fps = speed_up * fr * ds_ratio

    fr_stim_st = int(ds_ratio * t_stim_st)
    fr_stim_end = int(ds_ratio * t_stim_end)

    mv = cm.load(func_ch_file).resize(1, 1, ds_ratio)
    _min, _max = np.percentile(mv, 0.01), np.percentile(mv, 99.99)
    
    mv = np.array(255 * (mv - _min)/(1.1 * (_max - _min)), dtype = 'uint8')
    mv = mv[:,:,:,None] * np.ones(mv.shape + (3,))
    
    mcvid_filename = output_dir / f'{path}_{func_ch}_{speed_up}x-rigcorr_video.mp4'
    mv[fr_stim_st:fr_stim_end, anchor[0]:anchor[0] + ht, anchor[1]:anchor[1] + wd, 0] = 255
    imageio.mimwrite(mcvid_filename, mv.astype('uint8'), fps = fps,  quality=7) ###NOTE pip install imageio-ffmpeg


def _visualize_rigcorr_results(mc, mc_ch, mc_ch_file, figbasename):

    #1. 
    plt.figure()
    plt.plot(np.array(mc.shifts_rig)[:,0], label = 'x shifts')
    plt.plot(np.array(mc.shifts_rig)[:,1], label = 'y shifts')
    plt.legend()
    plt.xlabel('frames')
    plt.ylabel('pixels')

    plt.savefig(str(figbasename) + '_rigid-shifts.pdf')

    #2. 
    if mc.pw_rigid:
        _,ax=plt.subplots(2,1)
        ax[0].plot(np.array(mc.x_shifts_els) - np.array(mc.shifts_rig)[:,0,None])
        ax[0].set_title('x shift deviations')
        ax[1].plot(np.array(mc.y_shifts_els) - np.array(mc.shifts_rig)[:,1,None])
        ax[1].set_title('y shift deviations')

        plt.savefig(str(figbasename) + '_shift-deviations.pdf')
        
    
    #3. 
    corr2 = np.array(cm.load(mc.mmap_file))
    raw2 = np.array(cm.load_movie_chain([mc_ch_file]))

    c = corr2.reshape(corr2.shape[0], -1)
    r = raw2.reshape(raw2.shape[0], -1)

    def corr_m(x):
        xm = x.mean(axis=0)
        xm_ = xm - xm.mean()
        x_ = x - x.mean(axis=1)[:,None]
        corr = (x_ @ xm_) / np.sqrt((x_ @ x_.T).diagonal() * (xm_**2).sum())
        return corr

    c = corr_m(c)
    r = corr_m(r)

    fig, ax = plt.subplots(1,2, figsize = (10,5))
    ax[0].plot(c, label = 'corrected')
    ax[0].plot(r, label = 'raw')
    ax[0].set(xlabel = 'Frame', ylabel = 'Correlation with Mean')
    ax[0].legend()

    ax[1].scatter(x = r, y= c)
    xlim = ax[1].get_xlim()
    ylim = ax[1].get_ylim()
    nlim = ( min(xlim[0], ylim[0]), max(xlim[1], ylim[1]) )
    ax[1].plot(nlim, nlim, color = 'k', ls = '--')
    ax[1].set( ylabel = 'Corrected', xlabel = 'Raw', 
            title = 'Correlation with Mean', 
            xlim = nlim, ylim = nlim)

    sns.despine()
    fig.tight_layout(pad = 1.)
    fig.savefig(str(figbasename) + '_correlation-with-mean.pdf')



@capture_args
def rigid_motion_correction(provenance, z, affcorr_results, nprocs=None, max_shifts=(50, 50), niter_rig= 3, pw_rigid= True, shifts_opencv=True, border_nan= 'copy',
                            nonneg_movie=True, use_cuda=False, strides=(64, 64), overlaps=(32, 32), max_deviation_rigid=3,
                            upsample_factor_grid=4, mcvideo_params={}, **kwargs):
    
    """
    "max_shifts"  # maximum allowed rigid shift in pixels (view the movie to get a sense of motion)
    "niter_rig"          # number of times to perform rigid registration (i'd recommend doing at least 2 especially for these shorter recordings)
    "pw_rigid"       # flag for performing rigid or piecewise rigid motion correction (false for now as we want to asses rigid registration first)
    "shifts_opencv"    # flag for correcting motion using bicubic interpolation (otherwise FFT interpolation is used)
    "border_nan"
    "nonneg_movie"
    "use_cuda"
    "strides" # size of patches for nonrigid motion correction in pixels
    "overlaps" # number of pixrls of overlap between patches
    "max_deviation_rigid" # maximum allowed deviation of any individual patch's registered shift from the rigid shift
    "upsample_factor_grid"  
    """

    from caiman.motion_correction import MotionCorrect
    import pickle


    if not provenance['rigid_motion_correction']:
        provenance['rigid_motion_correction'] = {}

    if z not in provenance['rigid_motion_correction']:
        provenance['rigid_motion_correction'][z] = {}

    if 'filenames' in provenance['rigid_motion_correction'][z]:
        mc_obj_file = provenance['rigid_motion_correction'][z]['motion_correct_obj']
        with open(mc_obj_file, 'rb') as f:
            mc = pickle.load(f)
        return provenance, mc    

    output_dir = Path(provenance['output_dir']) / z
    output_dir.mkdir(exist_ok=True)
    prov = provenance['load_data']['args']
    multi_path, ch_dict, z = prov['multi_path'], prov['ch_dict'], prov['z']
    #affcorr_results_filenames = provenance['affine_motion_correction']['filenames']

    rigcorr_results_filenames = {}
    
    # concat_mc = np.concatenate(list(affcorr_results[ch_dict['mc_ch']].values()))
    # mc_fname = output_dir / f'concat_{ch_dict["mc_ch"]}-affcorr_results.ome.tif'
    # imsave(mc_fname, concat_mc)

    
    args_dict = kwargs['__args_dict'].copy()
    args_dict.pop("affcorr_results"); args_dict.pop('mcvideo_params'); args_dict.pop('z'); args_dict.pop('nprocs')


    _, dview, _ = cm.cluster.setup_cluster(
            backend='local', n_processes=nprocs, single_thread=False)

    #for i, p in enumerate(multi_path):
        #p = os.path.basename(p)

    rigcorr_results_filenames = {}

    #mc_fname = affcorr_results_filenames[ch_dict['mc_ch']][i]
    #func_fname = affcorr_results_filenames[ch_dict['func_ch']][i]
    mc_fname = (output_dir / "concat_mc.tif").as_posix()
    mc_concat = np.concatenate( list(affcorr_results[ch_dict['mc_ch']].values()) )
    imsave(mc_fname, mc_concat)

    func_fname = (output_dir / "concat_func.tif").as_posix()
    func_concat = np.concatenate( list(affcorr_results[ch_dict['func_ch']].values()) )
    imsave(func_fname, func_concat)

    mc = MotionCorrect(mc_fname, dview=dview, **args_dict) # function documention implies input should be str, but function handles ndarrays just fine
    mc.motion_correct(save_movie=True)

    border_to_0 = 0 if mc.border_nan == 'copy' else mc.border_to_0 

    mc_ch_basename = f'concat_{ch_dict["mc_ch"]}-rigcorr_struct-'
    rigcorr_results_filenames[ch_dict['mc_ch']] = cm.save_memmap(mc.mmap_file, base_name=mc_ch_basename, order='C',
                            border_to_0=border_to_0, dview=dview)

    # apply the shifts to the functional channel and save
    # concat_fc = np.concatenate(list(affcorr_results[ch_dict['func_ch']].values()))
    # func_fname = output_dir / f'concat_{ch_dict["func_ch"]}-affcorr_results.ome.tif'
    # imsave(func_fname, concat_fc)

    f_ch_basename = (output_dir / f'concat_{ch_dict["func_ch"]}-rigcorr_func-').as_posix()
    rigcorr_results_filenames[ch_dict['func_ch']] = mc.apply_shifts_movie(func_fname, 
                                                                    save_memmap=True, order = 'C', save_base_name=f_ch_basename)

    _save_rigid_motion_correction_video(output_dir, ch_dict['func_ch'], rigcorr_results_filenames[ch_dict['func_ch']], z, 'concat', **mcvideo_params)
        
    _visualize_rigcorr_results(mc, ch_dict['mc_ch'], mc_fname, output_dir / f'concat_{ch_dict["mc_ch"]}')

    mc_obj_file = output_dir / 'mc_obj.pkl'
    mc.dview = None
    with open(mc_obj_file, 'wb') as f:
        pickle.dump(mc, f)

    provenance['rigid_motion_correction'][z]['args'] = args_dict
    provenance['rigid_motion_correction'][z]['filenames'] = rigcorr_results_filenames
    provenance['rigid_motion_correction'][z]['motion_correct_obj'] = mc_obj_file

    cm.stop_server(dview=dview)

    _save_provenance(provenance)
    return provenance, mc



#
def _identify_rois(output_dir, func_ch_file, z, method='max', filt=True, kern=1, 
                    channels=[[0,0]], flow_threshold=2, cellprob_threshold=-1, diameter=15, 
                    model_type='cyto', show_figs=True):

    """
    "method" :'max', 
    "filt" : True, # whether or not to spatially filter the resulting image
    "kern" : 1,      # kernel size of filter 
    "channels" : [[0,0]], 
    "flow_threshold" : 2, 
    "cellprob_threshold" : -1, 
    "diameter" : 15, 
    "model_type" : 'cyto',
    'show_figs' : True   # show figures  
    """    

    from cellpose import models
    import cv2 as cv


    func = cm.load(func_ch_file)

    if method == 'max':
        func_lc = np.percentile(func, 99, axis=0)
    elif method == 'local_correlation':
        func_lc = func.local_correlations()
    elif method == 'mean':
        func_lc = np.mean(func, axis=0)
    else:
        print('unrecognized method')
        func_lc = np.zeros(func.shape[1:])
        
    if filt:
        func_lc = median_filter(func_lc, kern)

    if show_figs:
        plt.figure(figsize = (10,10))
        plt.imshow(func_lc)

    ###
    model = models.Cellpose(model_type=model_type, gpu=False)
    masks, _, _, _ = model.eval(func_lc,  diameter= diameter, channels=channels, 
                                flow_threshold = flow_threshold,
                                cellprob_threshold = cellprob_threshold)
    
    roi_masks = np.array([(masks==i).flatten('F') for i in np.sort(np.unique(masks))[1:]]).T

    #create image with masks for GUI purposes
    roi_img_bkg = (func_lc*190 // func_lc.max()).astype(np.uint8)
    roi_img_bkg = cv.cvtColor(roi_img_bkg, cv.COLOR_GRAY2RGB)

    roi_img_mask = np.zeros([*func_lc.shape,3], dtype=np.uint8)
    for i in roi_masks.T:
        roi_img_mask[i.reshape(func_lc.shape,order='F')] = np.tile(65*np.random.rand(1,3),(i.sum(),1)).astype(int)

    if show_figs:
        fig, ax=plt.subplots(1,2, figsize = (10,5))
        ax[0].imshow(roi_img_bkg + roi_img_mask)
        ax[1].imshow(roi_img_bkg)
        fig.tight_layout(pad = 1.)


    func_lc = func_lc

    roi_masks_file = output_dir / f'concat_roi-masks.npy'
    np.save(roi_masks_file, roi_masks)  

    return roi_masks, roi_masks_file, roi_img_bkg, roi_img_mask, func_lc
    


def _addremove_rois_manually(output_dir, mc_ch_rigcorr_file, z, roi_masks0, roi_img_bkg0, roi_img_mask0):
    """Press ESC to exit the GUI"""

    #NOTE need to make sure you're not running opencv headless
    
    roi_masks = roi_masks0.copy()
    roi_img_bkg = roi_img_bkg0.copy()
    roi_img_mask = roi_img_mask0.copy()

    while input('Would you like to remove any neurons (y/n)?  ').lower() in ['y','ye','yes']:
        print('Right click on neurons in the viewer that ')

        neurons, _ms = remove_neurons(roi_masks, roi_img_bkg, roi_img_mask.copy(), title=f'{z}')
        
        if input("Are you sure you'd like to remove these neurons (y/n)?  ").lower() in ['y','ye','yes']:
            print('deleting ', neurons)
            roi_masks = np.delete(roi_masks, neurons, 1)
            roi_img_mask = _ms


    Yr, dims, T = cm.load_memmap(mc_ch_rigcorr_file)
    mc_ch_rigcorr = np.reshape(Yr.T, [T] + list(dims), order='F')

    while input('Would you like to add more neurons (y/n)?  ').lower() in ['y','ye','yes']:
        _ms , mask = draw_masks(roi_img_bkg, roi_img_mask.copy(), np.zeros(mc_ch_rigcorr.shape[-2:], np.uint8), show_plot=False, title=f'{z}')
        
        if input("Are you sure you'd like to add this neuron (y/n)?  ").lower() in ['y','ye','yes']:
            print('adding...')
            roi_masks = np.concatenate([roi_masks, mask.reshape((-1,1), order='F')], axis=1)
            roi_img_mask = _ms

    
    roi_masks = roi_masks[:, ~(roi_masks.sum(axis=0)==0)]   #remove empty masks that were kept

    # show results
    fig, ax = plt.subplots(1,2, figsize = (10,5))
    ax[0].imshow(roi_img_bkg + roi_img_mask)
    ax[1].imshow(roi_img_bkg)
    fig.tight_layout(pad = 1.) 

    if input('Finish/Restart (y/n)?  ').lower() not in ['y','ye','yes']:
        plt.close(fig)
        return _addremove_rois_manually(output_dir, mc_ch_rigcorr_file, z, roi_masks0, roi_img_bkg0, roi_img_mask0)
    else:
        roi_masks_file = output_dir / f'concat_roi-masks.npy'
        np.save(roi_masks_file, roi_masks) 

        return roi_masks, roi_masks_file, roi_img_bkg, roi_img_mask    

 

def _run_cnmf(output_dir, z, func_ch_file, roi_masks, decay_time=1.8, p=2, nb=2, 
            rf=None, only_init=False, min_SNR=2.0, use_cnn=False, use_cuda=False, 
            K=300,  gSig=[10,10]):


    """
    'fr': MCVID_PARAMS['fr'],
    'decay_time': 1.8, # this should be set to 1.8 for GCamp6s, but can be changed to 0.4 for faster indicators
    'p': 2, # this must be 2 for GCamp6s, it can be set to 1 for faster indicators
    'nb': 2, # the number of background components, 
    'rf': None, #must be None for seeded mode
    'only_init':False, #must be false for seeded mode
    'min_SNR': 2.0,
    'use_cnn': False, # whether or not to use a convolutional neural network to classify rois as good or bad
    'use_cuda':False, # whether or not to use GPUs

    ## the rest of these are necessary parameters to set for that get ignored
    ## since we are seeding the algorithm for initialization
    'K': 300,  
    'gSig':[10,10]
    """
    inputs = locals()
    inputs.pop('output_dir')
    inputs.pop('z')
    inputs.pop('func_ch_file')
    inputs.pop('roi_masks')

    from caiman.source_extraction.cnmf import cnmf
    from caiman.source_extraction.cnmf import params

    opts = params.CNMFParams(params_dict=inputs)


    _, dview, n_processes = cm.cluster.setup_cluster(
        backend='local', n_processes=None, single_thread=False)


    # do an initial fit of the cnmf
    cnm = cnmf.CNMF(n_processes, params=opts, dview=dview, Ain=roi_masks)
    
    Yr, dims, T = cm.load_memmap(func_ch_file)
    f_ch_rigcorr = np.reshape(Yr.T, [T] + list(dims), order='F')

    cnm = cnm.fit(f_ch_rigcorr)

    # save
    cnmf_file = output_dir / f'concat_{z}_cnmf-out.hdf5'
    cnm.save(cnmf_file.as_posix()) 

    cm.stop_server(dview=dview)
    #cnm.dview=None

    return cnm, cnmf_file


def _save_source_extraction_video(cnm, z, output_dir):
    import imageio

    mv = np.rollaxis((cnm.estimates.A @ cnm.estimates.C).reshape((*cnm.dims,-1), order = 'F'), -1)
    _min, _max = mv.min(), mv.max()
    mv = np.array(255 * (mv - _min) / (_max - _min), dtype = 'uint8')
    
    src_extraction_file = output_dir / f'conat_{z}_src-extraction-video.mp4'
    imageio.mimwrite(src_extraction_file.as_posix(), mv, fps = 30,  quality=7) 


def _visualize_src_extraction_results(self, idx=[41]):    
    #view the initial contours to see if we need to change any parameters
    self.cnm.estimates.plot_contours(img=self.func_lc)
    
    # Visualize raw traces
    self.cnm.estimates.dims = self.cnm.dims
    self.cnm.estimates.view_components(img=self.func_lc, idx=idx)


@capture_args
def source_extraction(provenance, data_array, z, mc, idroi_params={}, runcnmf_params={}, **kwargs):

    import glob 

    if not provenance['source_extraction']:
        provenance['source_extraction'] = {}

    if z not in provenance['source_extraction']:
        provenance['source_extraction'][z] = {}    

    #if 'filenames' in provenance['source_extraction'][z]:
    #    return provenance     


    #_, dview, _ = cm.cluster.setup_cluster(
    #        backend='local', n_processes=None, single_thread=False)
    #mc.dview = dview

    prov = provenance['load_data']['args']
    ch_dict, z = prov['ch_dict'], prov['z']
    output_dir = Path(provenance['output_dir']) / z
    output_dir.mkdir(exist_ok=True)

    rigcorr_results_filenames = provenance['rigid_motion_correction'][z]['filenames']

    if False:
        pass
        # mc_files = []
        # func_files = []
        # mc_corr_files = []
        # func_corr_files = []
        #for z in zs:
        #     mc_fname = output_dir / f'temp/concat_{z}_mc.tif'
        #     func_fname = output_dir / f'temp/concat_{z}_fc.tif'
        #     mc_corr_basename = (output_dir / f'temp/concat_{z}_mc-corr').as_posix()
        #     func_corr_basename = (output_dir / f'temp/concat_{z}_fc-corr').as_posix()
            
        #     mc_corr_file = glob.glob(mc_corr_basename + '*')
        #     func_corr_file = glob.glob(func_corr_basename + '*')
        #     if  mc_corr_file and func_corr_file:
        #         mc_corr_file = mc_corr_file[0]
        #         func_corr_file = func_corr_file[0]
        #     else:
        #         z_ind = zs.index(z)
        #         mc_ind = list(ch_dict.keys()).index('mc_ch')
        #         func_ind = list(ch_dict.keys()).index('func_ch')
                
        #         all_mc = data_array[z_ind, :, mc_ind,...]
        #         all_func = data_array[z_ind, :, func_ind,...]

        #         concat_mc = np.concatenate([all_mc[j] for j in range(all_mc.shape[0])])
        #         concat_func = np.concatenate([all_func[j] for j in range(all_func.shape[0])])

        #         imsave(mc_fname, concat_mc)
        #         imsave(func_fname, concat_func)
                
        #         mc_corr_file = mc.apply_shifts_movie(mc_fname, save_memmap=True, order = 'C', save_base_name=mc_corr_basename)
        #         func_corr_file = mc.apply_shifts_movie(func_fname, save_memmap=True, order = 'C', save_base_name=func_corr_basename)
                

        #     mc_files.append(mc_fname)
        #     func_files.append(func_fname)
        #     mc_corr_files.append(mc_corr_file)
        #     func_corr_files.append(func_corr_file)

        # cm.stop_server(dview=dview)

    #for z, mc_corr_file, func_corr_file  in zip(zs, mc_corr_files, func_corr_files):
    mc_corr_file = rigcorr_results_filenames[ch_dict['mc_ch']] 
    func_corr_file = rigcorr_results_filenames[ch_dict['func_ch']] 

    roi_masks, _, roi_img_bkg, roi_img_mask, func_lc = _identify_rois(output_dir, func_corr_file, z, **idroi_params)

    roi_masks, roi_masks_file, roi_img_bkg, roi_img_mask  = _addremove_rois_manually(output_dir, mc_corr_file, z, roi_masks, roi_img_bkg, roi_img_mask)

    cnm, cnm_file =  _run_cnmf(output_dir, z, func_corr_file, roi_masks, **runcnmf_params)

    _save_source_extraction_video(cnm, z, output_dir)

    #_visualize_src_extraction_results() 

    #provenance['source_extraction']['args'] = kwargs['__args_dict']
    provenance['source_extraction'][z] = {}
    provenance['source_extraction'][z]['filenames'] = {
        'roi_masks_file': roi_masks_file,
        'cnm_file': cnm_file
    }
    # provenance['source_extraction']['aux_filenames'] = {
    #     'mc_files' : mc_files,
    #     'func_files' : func_files,
    #     'mc_corr_files': mc_corr_files,
    #     'func_corr_files': func_corr_files
    # }

    _save_provenance(provenance)
    return provenance
