"""
Shared fixtures for regression tests.

Regression tests require two things to be present on disk:
  1. ZH537 ground-truth analysis outputs  (ZH537_DIR / "analysis" / *.npy)
  2. Snapshot inputs generated by update_snapshots.py  (SNAPSHOTS_DIR / *.npy)

If either is missing the tests are skipped automatically.
Run  tests/regression/update_snapshots.py  once to generate the snapshots.
"""
import os
from pathlib import Path
import pytest
import numpy as np

_zh537_env = os.environ.get("ZH537_DIR", "")
ZH537_DIR     = Path(_zh537_env) if _zh537_env else None
SNAPSHOTS_DIR = Path(__file__).parent / "snapshots"


def _skip_if_missing(path: Path, reason: str):
    if not path.exists():
        pytest.skip(reason)


@pytest.fixture(scope="session")
def zh537_analysis_dir():
    if ZH537_DIR is None:
        pytest.skip("ZH537_DIR environment variable not set")
    d = ZH537_DIR / "analysis"
    _skip_if_missing(d, f"ZH537 analysis dir not found: {d}")
    return d


@pytest.fixture(scope="session")
def zh537_ground_truth(zh537_analysis_dir):
    """Load the stored ground-truth outputs from the ZH537 run."""
    def _load(name):
        p = zh537_analysis_dir / name
        _skip_if_missing(p, f"Ground truth file missing: {p}")
        return np.load(p, allow_pickle=True)

    return {
        "resp1":        _load("resp1.npy"),
        "resp2":        _load("resp2.npy"),
        "nums":         _load("nums.npy"),
        "z_ids_stim1":  _load("z_ids_stim1.npy"),
        "z_ids_both":   _load("z_ids_both.npy"),
        "z_ids_stim2":  _load("z_ids_stim2.npy"),
    }


@pytest.fixture(scope="session")
def zh537_snapshots():
    """
    Load the pre-computed snapshot arrays.
    Generate these by running:  python tests/regression/update_snapshots.py
    """
    _skip_if_missing(
        SNAPSHOTS_DIR / "stims1.npy",
        "Regression snapshots not found. Run: python tests/regression/update_snapshots.py"
    )
    return {
        "stims1":  np.load(SNAPSHOTS_DIR / "stims1.npy"),
        "stims2":  np.load(SNAPSHOTS_DIR / "stims2.npy"),
        "z_ids":   np.load(SNAPSHOTS_DIR / "z_ids.npy"),
        "params":  np.load(SNAPSHOTS_DIR / "params.npy", allow_pickle=True).item(),
        # Expected outputs computed from the same stims by update_snapshots.py
        "expected_resp1":      np.load(SNAPSHOTS_DIR / "expected_resp1.npy"),
        "expected_resp2":      np.load(SNAPSHOTS_DIR / "expected_resp2.npy"),
        "expected_nums":       np.load(SNAPSHOTS_DIR / "expected_nums.npy"),
        "expected_z_ids_stim1": np.load(SNAPSHOTS_DIR / "expected_z_ids_stim1.npy"),
        "expected_z_ids_both":  np.load(SNAPSHOTS_DIR / "expected_z_ids_both.npy"),
        "expected_z_ids_stim2": np.load(SNAPSHOTS_DIR / "expected_z_ids_stim2.npy"),
    }
